### PR TITLE
Update RepositoryActionHandler.groovy

### PR DESCRIPTION
**Pull request by kleino**
Hi, I would like my Hacktober-T-Shirt please to my home address, thank you :smile_cat:

### CODE REVIEW

**Comment by kleino** [comment]
I actually have no idea how to approve the CLA :sweat_smile:  how do I do that?

**Comment by aepfli** [comment]
https://github.com/aepfli/gradle-gitlab-repositories/blob/main/.clabot 

uh they changeds soemthing, add yourself here I think :D it used to be different :)

**Comment by aepfli** [comment]
or i can add you, as long as that is fine for you

ned to get rid of this bot it seems

**Comment by aepfli** [comment]
ah i merge it based on github terms and services, we are fine anyways

**Comment by kleino** [comment]
:bow: thank you!

**Pull request merged**
